package de.adis_portal.server.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportMetadataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportMetadataAllPropertiesEquals(ReportMetadata expected, ReportMetadata actual) {
        assertReportMetadataAutoGeneratedPropertiesEquals(expected, actual);
        assertReportMetadataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportMetadataAllUpdatablePropertiesEquals(ReportMetadata expected, ReportMetadata actual) {
        assertReportMetadataUpdatableFieldsEquals(expected, actual);
        assertReportMetadataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportMetadataAutoGeneratedPropertiesEquals(ReportMetadata expected, ReportMetadata actual) {}

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportMetadataUpdatableFieldsEquals(ReportMetadata expected, ReportMetadata actual) {
        assertThat(expected)
            .as("Verify ReportMetadata relevant properties")
            .satisfies(e -> assertThat(e.getRid()).as("check rid").isEqualTo(actual.getRid()))
            .satisfies(e -> assertThat(e.getMetadata()).as("check metadata").isEqualTo(actual.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportMetadataUpdatableRelationshipsEquals(ReportMetadata expected, ReportMetadata actual) {}
}
